build.gradle, src/main/java/com/fab/banggabgo/config/security/SecurityConfig.java, src/main/java/com/fab/banggabgo/controller/TestController.java, src/test/java/com/fab/banggabgo/controller/TestControllerTest.java
**AS-IS**
기본적인 Security Config 와 그에 대한 테스트를 작성하였습니다. 
**TO-BE**
- 로그인 
- Jwt 에대한 Security  설정
- Oauth 사용 고려
=> [002]-Security 

src/main/java/com/fab/banggabgo/type/ActivityTime.java, src/main/java/com/fab/banggabgo/type/Gender.java, src/main/java/com/fab/banggabgo/type/MatchStatus.java, src/main/java/com/fab/banggabgo/type/Mbti.java, src/main/java/com/fab/banggabgo/type/PreferredAge.java, src/main/java/com/fab/banggabgo/type/Seoul.java
**AS-IS**
공통적으로 사용하는 enum
**TO-BE**
=> [feat] Create enum

src/main/java/com/fab/banggabgo/common/ApiResponse.java, src/main/java/com/fab/banggabgo/common/Code.java
- Api Response 는 restApi가 반환할 공통형태에대한 틀을 제공합니디ㅏ.
- Code  추후 구현할 ExceptionCode, ResponseCode,등 사용자의 임의로 만든 CodeEnum 등을 일반화한 인터페이스 입니다.
**AS-IS**
RestApi 응답값 반환에대한 일반적인 규격 class를 제작하였습니다. 
파일에 포함된 Code는 추후 구현할 ExceptionCode , ResponseCode 의 인터페이스입니다.
**TO-BE**
=> add : Api Response

build.gradle, src/main/java/com/fab/banggabgo/config/PasswordEncoderConfig.java, src/main/java/com/fab/banggabgo/config/security/JwtAuthenticationFilter.java, src/main/java/com/fab/banggabgo/config/security/JwtTokenProvider.java, src/main/java/com/fab/banggabgo/config/security/SecurityConfig.java, src/main/java/com/fab/banggabgo/controller/SignController.java, src/main/java/com/fab/banggabgo/dto/EmailCheckResultDto.java, src/main/java/com/fab/banggabgo/dto/LogOutResultDto.java, src/main/java/com/fab/banggabgo/dto/NameCheckResultDto.java, src/main/java/com/fab/banggabgo/dto/SignInRequestDto.java, src/main/java/com/fab/banggabgo/dto/SignInRequestForm.java, src/main/java/com/fab/banggabgo/dto/SignInResultDto.java, src/main/java/com/fab/banggabgo/dto/SignUpRequestDto.java, src/main/java/com/fab/banggabgo/dto/SignUpRequestForm.java, src/main/java/com/fab/banggabgo/dto/TokenDto.java, src/main/java/com/fab/banggabgo/entity/User.java, src/main/java/com/fab/banggabgo/repository/UserRepository.java, src/main/java/com/fab/banggabgo/service/SignService.java, src/main/java/com/fab/banggabgo/service/impl/SignServiceImpl.java, src/main/resources/application.yml, src/main/resources/jwt.yml, src/test/java/com/fab/banggabgo/service/impl/SignServiceImplTest.java
**AS-IS**
origin 회원에대한 회원가입 및 로그인 기능구현
Swagger 를 통한 api 테스트  및 테스트 코드 작성
**TO-BE**
- 로그아웃 , 및 토큰만료시 로직 구현
=> feat : 회원가입 기능 구현 (Origin)

.github/workflows/ci-cd.yml, Dockerfile, build.gradle, src/test/java/com/fab/banggabgo/BanggabgoApplicationTests.java
**AS-IS**
CI-CD 를 구현하였습니다.
main , CI-CD(테스트) 브랜치로 push 시 작성된 코드를 gradle로 빌드하여 docker hub에 해당 빌드버전을 올리도록 작성하였습니다.
**TO-BE**
=> chore : CI-CD

banggapgo-docker/docker-compose.yml, src/main/java/com/fab/banggabgo/config/SwaggerConfig.java, src/main/resources/application-prod.yml, src/main/resources/jwt.yml
**AS-IS**
- login test 를위해 임시 배포 까지 구현하였습니다.
-  테스트환경의 헤더값을 api 명세서대로 변경하였습니다.
- 배포 api 는 임시로 8083 을사용하도록 작성되어있습니다.
**TO-BE**
=> 로그인 - test Deploy 

banggapgo-docker/docker-compose.yml, src/main/java/com/fab/banggabgo/config/CorsConfig.java, src/main/resources/application-prod.yml, src/main/resources/application.yml
**AS-IS**
- docker compose 세팅  로컬과 배포환경에서 추가세팅하였습니다.
- 로그인 api 연동에서 CORS 문제를 해결하기위해 설정을 추가하였습니다. 추후 서비스 배포시 수정이필요합니다.
**TO-BE**
-  response 시 일관성있는 api Response를 추가작성
=> fix : sign deploy

src/main/java/com/fab/banggabgo/common/RuntimeExceptionHandler.java, src/main/java/com/fab/banggabgo/config/SwaggerConfig.java, src/main/java/com/fab/banggabgo/config/security/SecurityConfig.java, src/main/java/com/fab/banggabgo/controller/ArticleController.java, src/main/java/com/fab/banggabgo/dto/ArticleRegisterDto.java, src/main/java/com/fab/banggabgo/dto/ArticleRegisterForm.java, src/main/java/com/fab/banggabgo/entity/Article.java, src/main/java/com/fab/banggabgo/entity/User.java, src/main/java/com/fab/banggabgo/repository/ArticleRepository.java, src/main/java/com/fab/banggabgo/service/ArticleService.java, src/main/java/com/fab/banggabgo/service/impl/ArticleServiceImpl.java, src/main/java/com/fab/banggabgo/type/Gender.java, src/main/java/com/fab/banggabgo/type/Period.java, src/main/java/com/fab/banggabgo/type/Seoul.java, src/test/java/com/fab/banggabgo/controller/ArticleControllerTest.java, src/test/java/com/fab/banggabgo/service/impl/ArticleServiceImplTest.java
**AS-IS**
- Gender, Seoul Enum 수정했습니다. value 설정 및 fromValue 메서드 추가
- Article 엔티티 생성하고, User 엔티티에 articleList 추가했습니다.
- 글 등록시 글 양식 검증을 합니다.(글 제목과 내용이 비어있는지 체크, 가격 0 보다 큰지 체크, 지역 성별 올바른지 체크)
- JWT 토큰으로 User를 불러올 때 User가 존재하지 않으면 RuntimeException 에러가 발생합니다.
- SwaggerConfig, SecurityConfig 수정했습니다.
- RuntimeException에 대한 ExceptionHandler를 추가했습니다.
- Swagger로 테스트 완료했고, 테스트 코드 작성하여 테스트 진행했습니다.
**TO-BE**
- 글 목록 불러오기
=> feat : Article Register

src/main/java/com/fab/banggabgo/common/ApiResponse.java, src/main/java/com/fab/banggabgo/common/Code.java, src/main/java/com/fab/banggabgo/common/ResponseCode.java, src/main/java/com/fab/banggabgo/common/exception/CustomException.java, src/main/java/com/fab/banggabgo/common/exception/CustomExceptionHandler.java, src/main/java/com/fab/banggabgo/common/exception/ErrorCode.java, src/main/java/com/fab/banggabgo/common/exception/RuntimeExceptionHandler.java, src/main/java/com/fab/banggabgo/controller/SignController.java, src/main/java/com/fab/banggabgo/repository/UserRepository.java, src/main/java/com/fab/banggabgo/service/impl/SignServiceImpl.java, src/test/java/com/fab/banggabgo/service/impl/SignServiceImplTest.java
**AS-IS**
- BE,FE 소통시 에러코드 확인이 필요하여 ErrorCode, ApriResponse 를 적용하였습니다.
- 공통 코드 작성으로 ErrorCode 에 추가적으로 커스텀 에러코드를 지정할수있습니다.
- ApiReponse 를 개선하여 ApiResponseBuilder -> ResponseEntity 로 호환되도록 빌드코드를 추가하였습니다. 기존코드 마이그래이션시 ApiResponseBuilder 의 .build() 시 ApiResponse .toEntity()시 ResponseEntity로 반환됩니다. 
- 마이그래이션 로직은 SignController 부분에 적용되어있습니다.
**TO-BE**
=> Common - 공통코드 ApiResponse & Code Impl

src/main/java/com/fab/banggabgo/common/ApiResponse.java, src/main/java/com/fab/banggabgo/common/Code.java, src/main/java/com/fab/banggabgo/common/ResponseCode.java, src/main/java/com/fab/banggabgo/common/exception/CustomException.java, src/main/java/com/fab/banggabgo/common/exception/CustomExceptionHandler.java, src/main/java/com/fab/banggabgo/common/exception/ErrorCode.java, src/main/java/com/fab/banggabgo/common/exception/RuntimeExceptionHandler.java, src/main/java/com/fab/banggabgo/controller/SignController.java, src/main/java/com/fab/banggabgo/repository/UserRepository.java, src/main/java/com/fab/banggabgo/service/impl/SignServiceImpl.java, src/test/java/com/fab/banggabgo/service/impl/SignServiceImplTest.java
**AS-IS**
-  ApiReponse를 통한 일관성 있게 반환하도록 수정한 커밋이 포함되어있습니다.
-  sign test 로직 변경이 추가되어있습니다.
-  sign login 검증 로직이 변경되어있습니다.
**TO-BE**
=> refactor : ApiResponse 를 통한 일관성 있는 반환

src/main/java/com/fab/banggabgo/config/SwaggerConfig.java, src/main/java/com/fab/banggabgo/controller/MyContentController.java, src/main/java/com/fab/banggabgo/dto/mycontent/FavoriteArticleDto.java, src/main/java/com/fab/banggabgo/dto/mycontent/MyArticleDto.java, src/main/java/com/fab/banggabgo/dto/mycontent/MyInfoDto.java, src/main/java/com/fab/banggabgo/entity/User.java, src/main/java/com/fab/banggabgo/repository/ArticleRepositoryCustom.java, src/main/java/com/fab/banggabgo/repository/impl/ArticleRepositoryImpl.java, src/main/java/com/fab/banggabgo/service/MyContentService.java, src/main/java/com/fab/banggabgo/service/impl/MyContentServiceImpl.java, src/test/java/com/fab/banggabgo/controller/MyContentControllerTest.java, src/test/java/com/fab/banggabgo/service/impl/MyContentServiceImplTest.java, src/test/java/com/fab/banggabgo/service/impl/UserDetailsServiceImplTest.java
**AS-IS**
**TO-BE**
- MyContent Controller, Service가 추가되었습니다.
- 구현기능
- 내 게시물 가져오기 
- 내가 좋아요한 게시물 가져오기
- 내정보 가져오기
Swagger Api를 통한 테스트를 진행하였으며 더미파일을 통한 테스트를 진행하였습니다. 추후 프론트 연동이후 추가 테스트케이스가 필요할것같습니다. 🤔
=> feat :  MyContent ✨

src/main/java/com/fab/banggabgo/controller/ArticleController.java, src/main/java/com/fab/banggabgo/repository/ArticleRepositoryCustom.java, src/main/java/com/fab/banggabgo/repository/impl/ArticleRepositoryImpl.java, src/main/java/com/fab/banggabgo/service/ArticleService.java, src/main/java/com/fab/banggabgo/service/impl/ArticleServiceImpl.java, src/test/java/com/fab/banggabgo/controller/ArticleControllerTest.java, src/test/java/com/fab/banggabgo/service/impl/ArticleServiceImplTest.java
**AS-IS**
- ArticleServiceImpl, ArticleServiceImplTest 파일에 JwtTokenProvider, UserRepository 존재(필요 x)
**TO-BE**
- ArticleServiceImpl, ArticleServiceImplTest 파일에 JwtTokenProvider, UserRepository 삭제
- 게시글 총 개수 구하기 기능 구현
=> feat : 게시글 총 개수 구하기 기능 구현

src/main/java/com/fab/banggabgo/dto/mycontent/FavoriteArticleDto.java, src/main/java/com/fab/banggabgo/dto/mycontent/MyArticleDto.java, src/main/java/com/fab/banggabgo/dto/mycontent/MyInfoDto.java
**AS-IS**
- myinfo 의 User tags를 부르지않음
- FE postcard 를 불러오기에 데이터가 부족한 부분이 있음
**TO-BE**
- [#34](https://github.com/Team-FAB/FAB-BE/issues/34) 의 issue 에대한 수정입니다.
- 기존 누락된 유저관련 칼럼들이 추가되었습니다.
- myInfo 의 tags누락분이 추가되었습니다.
=> fix: fix #34

src/main/java/com/fab/banggabgo/controller/MyContentController.java, src/main/java/com/fab/banggabgo/dto/mycontent/PatchMyNicknameDto.java, src/main/java/com/fab/banggabgo/dto/mycontent/PatchMyNicknameForm.java, src/main/java/com/fab/banggabgo/dto/mycontent/PatchMyNicknameResult.java, src/main/java/com/fab/banggabgo/service/MyContentService.java, src/main/java/com/fab/banggabgo/service/impl/MyContentServiceImpl.java, src/test/java/com/fab/banggabgo/controller/MyContentControllerTest.java, src/test/java/com/fab/banggabgo/service/impl/MyContentServiceImplTest.java
변경사항
AS-IS
TO-BE
닉네임 변경기능 추가
테스트
-  테스트 코드[x]
-  API 테스트[x]
Swagger 를 통해 테스트를 진행하였습니다.
=> 010 profile

src/main/java/com/fab/banggabgo/controller/ArticleController.java, src/main/java/com/fab/banggabgo/repository/LikeArticleRepository.java, src/main/java/com/fab/banggabgo/service/ArticleService.java, src/main/java/com/fab/banggabgo/service/impl/ArticleServiceImpl.java, src/test/java/com/fab/banggabgo/controller/ArticleControllerTest.java, src/test/java/com/fab/banggabgo/service/impl/ArticleServiceImplTest.java
**TO-BE**
- User Id와 Article Id를 받으면 LikeArticle에 해당 찜 내역이 있는지 확인합니다. 있으면 해당 찜을 삭제하고, 없으면 찜 정보를 생성합니다.
- Swagger로 API 테스트 진행했고, Controller, Service 테스트 코드 작성했습니다.
유저가 찜하지 않은 글에 요청을 보내면 찜이 되는지, 찜한 글에 요청을 보내면 찜이 삭제 되는지 테스트. 찜한 여부 올바르게 가져오는지 테스트.
=> 013 article like

src/main/java/com/fab/banggabgo/common/exception/ErrorCode.java, src/main/java/com/fab/banggabgo/controller/MyContentController.java, src/main/java/com/fab/banggabgo/dto/mycontent/MyInfoDto.java, src/main/java/com/fab/banggabgo/dto/mycontent/PatchMyInfoDto.java, src/main/java/com/fab/banggabgo/dto/mycontent/PatchMyInfoForm.java, src/main/java/com/fab/banggabgo/dto/mycontent/PatchMyInfoResultDto.java, src/main/java/com/fab/banggabgo/repository/impl/UserRepositoryImpl.java, src/main/java/com/fab/banggabgo/service/MyContentService.java, src/main/java/com/fab/banggabgo/service/impl/MyContentServiceImpl.java, src/test/java/com/fab/banggabgo/controller/MyContentControllerTest.java, src/test/java/com/fab/banggabgo/service/impl/MyContentServiceImplTest.java
**AS-IS**
**TO-BE**
- 내정보를 수정 하는 기능이 추가됩니다.
- swagger 를 통해 form 데이터 가 정상인경우 , 데이터 누락이 있는경우에 대해 테스트 하였습니다.
=> feat: patch MyInfo

src/main/java/com/fab/banggabgo/dto/mycontent/MyInfoDto.java, src/main/java/com/fab/banggabgo/repository/impl/ArticleRepositoryImpl.java
- MyArticle 정렬기준변경 
- MyinfoDto 누락된 Mbti 값 추가
=> Refector: fix

src/main/java/com/fab/banggabgo/service/impl/SignServiceImpl.java
=> refact: 토큰 메서드 추출

src/main/java/com/fab/banggabgo/controller/SignController.java, src/main/java/com/fab/banggabgo/dto/OAuth2/OAuth2ProfileDto.java, src/main/java/com/fab/banggabgo/dto/OAuth2/OAuth2SignInRequestDto.java, src/main/java/com/fab/banggabgo/dto/OAuth2/OAuth2SignInRequestForm.java, src/main/java/com/fab/banggabgo/dto/mycontent/MyInfoDto.java, src/main/java/com/fab/banggabgo/entity/User.java, src/main/java/com/fab/banggabgo/service/SignService.java, src/main/java/com/fab/banggabgo/service/impl/SignServiceImpl.java, src/main/resources/application.yml, src/test/java/com/fab/banggabgo/service/impl/SignServiceImplTest.java
**AS-IS**
kakao의 acces_token을 받아서 로그인처리
**TO-BE**
kakao의 code를 받아서 로그인 처리
=> 014 o auth2

src/main/java/com/fab/banggabgo/common/exception/ErrorCode.java, src/main/java/com/fab/banggabgo/repository/impl/UserRepositoryImpl.java, src/main/java/com/fab/banggabgo/service/impl/RecommendServiceImpl.java, src/test/java/com/fab/banggabgo/service/impl/RecommendServiceImplTest.java
**AS-IS**
- 프로필이 일치하는 유저면 추천
- 유저의 프로필 정보가 null일 경우 에러 처리 없음
**TO-BE**
- 유저의 프로필 정보가 null이면 Custom Exception
- 게시글을 작성한 내역이 있는 유저만 추천하도록 수정
- test도 수정 사항에 맞춰 적용
게시글 작성한 적이 없는 유저 목록이 안 뜨는지 테스트. 프로필 정보가 null인 유저가 요청을 보낼 경우 Custom Error가 발생하는지 테스트.
=> fix : 프로필 추천하기 수정

src/main/java/com/fab/banggabgo/controller/UserController.java, src/main/java/com/fab/banggabgo/dto/user/ProfileDto.java, src/main/java/com/fab/banggabgo/service/UserService.java, src/main/java/com/fab/banggabgo/service/impl/UserServiceImpl.java, src/test/java/com/fab/banggabgo/controller/UserControllerTest.java, src/test/java/com/fab/banggabgo/service/impl/UserServiceImplTest.java
**TO-BE**
- 유저의 id 값을 받아서 해당 유저의 프로필 정보 불러오는 기능 구현
- 유저가 존재하지 않을 경우 Custom Exception 발생
존재하는 유저의 id값을 넣어 요청을 보낼 경우 프로필 정보 가져오는지 테스트.
존재하지 않는 유저의 id값을 넣어 요청을 보낼 경우 Error가 발생하는지 테스트.
=> feat : 유저 프로필 정보 불러오기 기능 구현

src/main/java/com/fab/banggabgo/controller/ArticleController.java, src/main/java/com/fab/banggabgo/dto/article/ArticleInfoDto.java, src/main/java/com/fab/banggabgo/repository/ArticleRepositoryCustom.java, src/main/java/com/fab/banggabgo/repository/impl/ArticleRepositoryImpl.java, src/main/java/com/fab/banggabgo/service/ArticleService.java, src/main/java/com/fab/banggabgo/service/impl/ArticleServiceImpl.java, src/test/java/com/fab/banggabgo/controller/ArticleControllerTest.java, src/test/java/com/fab/banggabgo/service/impl/ArticleServiceImplTest.java
**TO-BE**
- 유저가 작성한 게시글 중 모집중이고, 삭제되지 않은 글 목록을 불러옵니다.
- 게시글 id, 제목 리스트를 응답합니다.
- Swagger로 API 테스트하고, 테스트 코드 작성했습니다.
Swagger로 유저가 작성한 게시글의 id, 제목 목록이 가져와지는지 테스트 했습니다.
DB에 게시글의 isRecruiting, isDeleted 값이 바뀌면 응답 내용이 바뀌는지 테스트 했습니다.
존재하지 않는 유저 id로 요청을 보냈을 때 에러가 발생하는지 테스트 했습니다.
=> 024 users article

src/main/java/com/fab/banggabgo/service/MyContentService.java, src/test/java/com/fab/banggabgo/controller/MyContentControllerTest.java
=> fix : conflict가 발생하는 코드 해결

src/main/java/com/fab/banggabgo/dto/user/RecommendResponseDto.java, src/main/java/com/fab/banggabgo/service/impl/UserServiceImpl.java
**TO-BE**
- 프로필 추천 불러오기 응답에 자신의 닉네임도 추가
응답으로 자신의 닉네임도 가져오는지 테스트
=> feat : 프로필 추천 자신의 닉네임도 추가

src/main/java/com/fab/banggabgo/dto/OAuth2/OAuth2SignInResultDto.java, src/main/java/com/fab/banggabgo/service/SignService.java, src/main/java/com/fab/banggabgo/service/impl/SignServiceImpl.java
**AS-IS**
로그인시 token값 반환
**TO-BE**
로그인시 email, nickName, token값
=> style: api response에 email, nickname 추가

src/main/java/com/fab/banggabgo/common/ApiResponse.java
**TO-BE**
추후 와일드카드 제거를 위한 ApiResponse 를 개선하였습니다.
추후 사용시 기존컨트롤러에서 반환하는 ResponseEntity<?> 를 ReponseEntity<ApiResponse<T>> 형태로 사용할수있도록 변경하였습니다.  만약 보낼 데이터가없을경우 Object 로사용하시면 됩니다
=> Refactoring -ApiResponse 개선

src/main/java/com/fab/banggabgo/dto/article/ArticlePageDto.java
**AS-IS**
- ArticlePageDto에 유저 image 정보 누락
**TO-BE**
- 유저 image 정보도 응답하도록 추가
=> feat : 게시글 목록 불러오는 dto에 유저의 image 정보 추가

src/main/java/com/fab/banggabgo/common/exception/ErrorCode.java, src/main/java/com/fab/banggabgo/controller/ApplyController.java, src/main/java/com/fab/banggabgo/dto/apply/ApplyListResultDto.java, src/main/java/com/fab/banggabgo/dto/apply/ApplyPageDto.java, src/main/java/com/fab/banggabgo/entity/Apply.java, src/main/java/com/fab/banggabgo/repository/ApplyRepositoryCustom.java, src/main/java/com/fab/banggabgo/repository/impl/ApplyRepositoryImpl.java, src/main/java/com/fab/banggabgo/service/impl/ApplyServiceImpl.java, src/main/java/com/fab/banggabgo/service/impl/ArticleServiceImpl.java, src/test/java/com/fab/banggabgo/controller/ApplyControllerTest.java, src/test/java/com/fab/banggabgo/service/impl/ApplyServiceImplTest.java
**AS-IS**
isApply 가 신청 되었을경우 false, 신청 안되었을 경우 true
**TO-BE**
isApply 가 신청 되었을경우 true, 신청 안되었을 경우 false
=> fix: isApply true가 등록된으로 설정

src/main/java/com/fab/banggabgo/common/exception/ErrorCode.java, src/main/java/com/fab/banggabgo/controller/ChatRoomController.java, src/main/java/com/fab/banggabgo/dto/chat/ChatDto.java, src/main/java/com/fab/banggabgo/dto/chatRoom/ChatRoomPostResponseDto.java, src/main/java/com/fab/banggabgo/dto/chatRoom/GetMateListResponseDto.java, src/main/java/com/fab/banggabgo/dto/chatRoom/MateDto.java, src/main/java/com/fab/banggabgo/dto/user/UserDto.java, src/main/java/com/fab/banggabgo/entity/Mate.java, src/main/java/com/fab/banggabgo/entity/chat/Chat.java, src/main/java/com/fab/banggabgo/repository/MateRepository.java, src/main/java/com/fab/banggabgo/repository/MateRepositoryCustom.java, src/main/java/com/fab/banggabgo/repository/impl/MateRepositoryImpl.java, src/main/java/com/fab/banggabgo/service/impl/ChatRoomServiceImpl.java, src/main/java/com/fab/banggabgo/service/impl/ChatServiceImpl.java, src/test/java/com/fab/banggabgo/controller/ChatRoomControllerTest.java, src/test/java/com/fab/banggabgo/service/impl/ChatRoomServiceImplTest.java
**AS-IS**
**TO-BE**
채팅방을 생성하고, 채팅방 list를 불러오는 api
정상적인실행,  유저가 로그인하지 않은경우, apply가 본인이 아닐경우, apply가 승인상태가 아닐경우
정상적인 요청, 로그인 하지 않았을경우
=> 030 chat room

src/main/java/com/fab/banggabgo/dto/apply/ApplyDeleteNoticeResultDto.java
**AS-IS**
**TO-BE**
알림을 읽음으로 표시하는 dto
=> fix: 알림을 읽음으로 표시하는 dto

src/main/java/com/fab/banggabgo/controller/ApplyController.java, src/main/java/com/fab/banggabgo/controller/ArticleController.java, src/main/java/com/fab/banggabgo/controller/ChatRoomController.java, src/main/java/com/fab/banggabgo/controller/ExceptionController.java, src/main/java/com/fab/banggabgo/controller/MyContentController.java, src/main/java/com/fab/banggabgo/controller/TestController.java, src/main/java/com/fab/banggabgo/controller/UserController.java, src/main/java/com/fab/banggabgo/dto/article/ArticleEditForm.java, src/main/java/com/fab/banggabgo/dto/article/ArticleRegisterForm.java, src/main/java/com/fab/banggabgo/dto/mycontent/PatchMyInfoForm.java, src/main/java/com/fab/banggabgo/dto/mycontent/PatchMyNicknameForm.java
- 각 컨트롤러에 대한 Swagger 를 적용하였습니다.
- Swagger 가 적용되어있지않은 Controller 에 Swagger 설명을 하였습니다. 검증이 필요합니다. ( 수정 될수있음)
=> docs: Controller Swagger 적용

.github/workflows/ci-cd.yml, banggapgo-docker/api/Dockerfile, banggapgo-docker/docker-compose.yml, banggapgo-docker/nginx/config/nginx.conf
**AS-IS**
- main에 push가 일어날 때 Docker Image build, push
**TO-BE**
- EC2 인스턴스에 접속하여 Docker compose up을 해서 서버 배포
EC2 인스턴스 생성하여 서버 실행이 되는 것을 테스트 했습니다.
=> fix : main에 push가 일어날 때 ec2로 배포 CICD 구현

src/main/java/com/fab/banggabgo/config/security/SecurityConfig.java
**TO-BE**
- web.ignoring().requestMatchers(PathRequest.toStaticResources().atCommonLocations()) 추가
=> add : ignore favicon.ico

.github/workflows/ci-cd.yml
=> fix : ec2 docker pull 추가

.github/workflows/ci-cd.yml
fix : docker pull 삭제, docker compose up 옵션 변경
=> fix : docker pull 삭제, docker compose up 옵션 변경

src/main/java/com/fab/banggabgo/dto/mycontent/FavoriteArticleDto.java, src/main/java/com/fab/banggabgo/dto/mycontent/MyArticleDto.java
**AS-IS**
- FavoriteArticleDto, MyArticleDto에서 gender를 Article의 gender 값을 가져옴
**TO-BE**
- Article의 User의 gender 값을 가져오도록 변경
=> fix : FavoriteArticleDto, MyArticleDto gender 수정

.github/workflows/ci-cd.yml
**AS-IS**
- build 후에 수정내용이 서버에 반영 안됨.
**TO-BE**
- docker pull을 받아와 이미지 최신 버전으로 받아옴.
=> add : docker pull 추가

src/main/java/com/fab/banggabgo/service/impl/SignServiceImpl.java
**AS-IS**
**TO-BE**
web client exception logging 처리
=> refactor: web client exception logging 처리

src/main/java/com/fab/banggabgo/service/impl/SignServiceImpl.java
=> fix: web client 에러 확인

src/main/resources/oauth2-prod.yml
**AS-IS**
**TO-BE**
web client yml 버전
=> fix: web client 배포 버전 yml

banggapgo-docker/nginx/config/nginx.conf
**AS-IS**
- client_max_body_size 설정이 없어 1M 넘는 파일 업로드 불가
**TO-BE**
- client_max_body_size 10M로 설정
=> add : client_max_body_size 설정 추가
